#!/bin/python3

from random import randint
# input from player
player = input('rock(r), paper(p) or scissor(s)?')

print(player, 'vs', end=' ')

#code for generating a random computer choice
chosen = randint(1,3)

if chosen == 1:
    computer = 'r'
  
elif chosen == 2:
    computer = 'p'
  
else:
    computer = 's'

print(computer)

#Comparison of choices

if player == computer:
    print('DRAW!')
  
elif player == 'r' and computer == 's':
    print('Player wins!')

elif player == 'r' and computer == 'p':
    print('Computer wins!')
  
elif player == 'p' and computer == 's':
    print('Player wins!')
  
elif player == 'p' and computer == 'r':
    print('Computer wins!')
  
elif player == 's' and computer == 'r':
    print('Player wins!')
  
else:
    print('Computer wins!')
